### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cfey**
Fixes typo and adds custom header section to readme

### CODE REVIEW

**Comment by andyhite** [comment]
👍  thanks! Merging.

**Comment by andyhite** [comment]
I didn't think about how much of a drawback it is to require re-stating the content-type and accepts headers. If you want to take a crack at merging the headers provided to the createMiddleware argument into the default headers, that would be great. If not, I'll take a look at it this weekend.

**Comment by cfey** [comment]
I can have a look at this if you don't mind.

Btw. how do I set a header on runtime?
For example when the user logged in I want to set a token in the header as authorization

**Comment by andyhite** [comment]
It isn't very well documented, but the payload for any of the actions can take a `headers` key. So this would work:

``` js
dispatch(apiActions.write(foo, {
  headers: {
    'Authorization': 'Token token=12345',
  },
});
```

I usually do this in a custom middleware in the application. Here's an example from a project I just recently worked on:

``` js
import { apiActions } from 'redux-jsonapi';
import { authActions } from '../modules';

function createMiddleware() {
  const authorizedActions = [
    apiActions.GET,
    apiActions.POST,
    apiActions.PATCH,
    apiActions.DELETE,
  ];

  const addAuthorizationHeader = (action, token) => {
    return {
      ...action,
      payload: {
        ...action.payload,
        headers: {
          ...action.payload.headers,
          'Authorization': `Token token=${token}`,
        },
      },
    };
  };

  return (store) => (next) => (action) => {
    if (authorizedActions.indexOf(action.type)) {
      const { auth } = store.getState();

      if (auth.token) {
        return next(addAuthorizationHeader(action, auth.token));
      }
    }

    return next(action);
  };
}

export default createMiddleware;
```

It checks all actions being dispatched, and if it sees one of the `redux-jsonapi` action types, it appends the auth token to the action's header payload.

**Pull request merged**
